#
###################################
# Site wide configuration
####################################
#
title: Nina Belikova's Pacific Plains
email:
description: A blog in which I write about my iOs and web development misadventures.
#url: http://ninabelikova.github.io/leonids
url: http://blog.ninabelikova.com
#url: http://localhost:4000

#
###################################
# Jekyll configuration
####################################
#
markdown:    kramdown
highlighter:  rouge
excerpt_separator: <!--more-->

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Nina Belikova
#  avatar: avatar.jpg
  job: "Eats cheese and drink malta"
  bio: "Adventures and misadventures."
  email:
  disqus-shortname: ninabelikova
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics: 'UA-74369185-1'
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: ninabelikova
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: ninabelikova
